#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

if [ -x $HOME/.local/bin/dual_monitor ];then
    dual_monitor
fi

# NOTE the path to the polybar executable.  This is the default location
# when compiling from source.
if [ -x /usr/local/bin/polybar ]; then
    bash bspbar
fi

## Configurations -------------------------------#
bspc monitor eDP1 -d 󰈹 󰨞 󰆍 󰅎 󰉋 󰝚 󰒓
bspc monitor HDMI1 -d 8 9 0

bspc config border_width 2
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a kitty desktop='^3' follow=on focus=on

# 2 > web
bspc rule -a firefox desktop='^1' follow=on focus=on

# 2 > web
bspc rule -a Code desktop='^2' follow=on focus=on

# 3 > file
bspc rule -a Pcmanfm desktop='^5' follow=on focus=on

# 3 > file
bspc rule -a Geany desktop='^4' follow=on focus=on

# 6 > settings
bspc rule -a GParted desktop='^7' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^7' state=floating follow=on focus=on; done

# special rules
bspc rule -a kitty-float state=floating follow=on focus=on center=true rectangle=700x400+0+0
bspc rule -a kitty-nvim desktop='^2' follow=on focus=on
bspc rule -a kitty-player desktop='^6' state=floating follow=on focus=on rectangle=500x250+855+510
bspc rule -a kitty-player2 desktop='^6' state=floating follow=on rectangle=700x250+5+510
bspc rule -a Pcmanfm state=floating follow=on focus=on
bspc rule -a Onboard state=floating follow=on focus=on
bspc rule -a Audacious state=floating follow=on focus=on
bspc rule -a Firefox:Places state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on
bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off


## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
#dunst \
-geom "250x50-10+34" -frame_width "1" -font "JetBrainsMono Nerd Font Mono 9" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

deadd-notification-center &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr
xinput set-button-map 10 1 1 3 4 5 6 7 &

# Restore wallpaper
bash $HOME/.fehbg

xidlehook \
--not-when-fullscreen \
--not-when-audio \
--timer 300 'betterlockscreen -l blur -t "Contraseña"' '' &


# Start mpd
exec mpd &

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &
